questions = [
        ["Om du måste välja bara ett alternativ, hur vill du helst att andra uppfattar dig?",
         ["Som snäll", "Som smart", "Som korrekt", "Som kul"]],
        ["Vilket skulle vara värst om någon trodde det om dig? Att du är…",
         ["…korkad", "…elak", "…tråkig", "…slarvig"]],
        ["Vad passar bäst in på dig?",
         ["Tuff & envis", "Omtänksam & konflikträdd", "Spontan & tanklös",
          "Ordningsam & kritisk"]],
        ["Du ska ut och campa ett par nätter med några vänner. Vad bidrar du med i gruppen?",
         [
                 "Jag har koll på att vi ställer upp tältet på en bra plats och ser till att vi följer instruktionerna så det byggs upp på rätt sätt.",
                 " Jag är förmodligen den bestämt hur vi ska organisera allt och beslutat hur vi ska ta oss dit för att det ska gå snabbt och smidigt.",
                 "Jag tar med lite smått och gott som någon i gänget kan komma att behöva. T.ex. powerbanks i fall någons mobil laddar ur, värktabletter och plåster.",
                 "Jag kanske fixar en spellista med skön musik och när vi kommer fram föreslår jag roliga lekar och kommer på att vi ska nattbada."]],
        [
                "Du har fått ett stipendium till en tvåveckors sommarkurs utomlands. Det finns ett stort urval av platser och kurser att välja på. Hur gör du valet?",
                [
                        "Jag väljer en plats som erbjuder en kurs som jag kommer ha nytta av i framtiden.",
                        "Jag googlar och tittar på bilder från de olika platserna och väljer en kurs och en plats som känns kul och spännande.",
                        "Jag samlar fakta och läser på ordentligt om de olika kurserna och platserna innan jag fattar mitt beslut",
                        "Jag frågar mina kompisar om råd och försöker hitta information om vilka kurser som ger mysigast gemenskap."]],
        [
                "Några i klassen har fått i uppgift att hålla i en idrottslektion utan att läraren är med. När lektionen ska börja blir det tydligt att de inte gjort ett bra jobb, de har ingen plan och ingen vet vad ni ska göra. Vissa blir missnöjda och situationen börjar urarta. Vad gör du?",
                [
                        "Jag försöker lugna de som blir upprörda, samtidigt som jag försöker stötta de som är ansvariga genom att försiktigt fråga om jag kan hjälpa till med något.",
                        "Jag försöker antingen styra upp hur vi bör göra för att få ut något av lektionen, eller har jag redan hittat något bättre att lägga min tid på.",
                        "Jag låter andra lösa kaoset på plats men erbjuder mig när läraren senare undrar om någon kan ta fram en checklista på hur detta bör göras för att undvika oreda nästa gång.",
                        "Jag tycker det kan vara kul med oväntade situationer och tar det som det kommer. Jag passar nog bara på att ta det lugnt och snacka med mina vänner."]],
        [
                "Klassen har fått i uppgift att gruppvis göra förslag till en ny broschyr om er skola. Den broschyr som läraren gillar bäst kommer att tryckas och delas ut vid öppet hus och liknande. Vad tänker du och vilken roll tar du i gruppen? ",
                [
                        "Älskar grupparbeten! Jag tycker det är viktigt att vi visar en härlig känsla i broschyren så jag kommer nog med idéer på hur vi kan få fram det. Det vore också kul om vi gjorde broschyren på något nytt sätt, kanske som en app. ",
                        "Kan bli en roligt även om jag gärna jobbar själv. Hoppas vi kan dela upp arbetet så att jag kan fokusera på det jag vill i lugn och ro. Troligen ansvarar jag för att all fakta i texterna stämmer och att bilderna har korrekt upplösning och sådana saker.",
                        "Roligt, det blir säkert bra! Jag har lätt för att komma överens med alla i grupparbeten. Jag hjälper jag gärna till med det som behövs mest så att allt funkar bra. Det viktigaste är att vi har trevligt.",
                        "Vore kul om vår grupp tar hem det! Hoppas att alla gör vad de ska, så att vi inte behöver långa möten. Jag ser till att få genomföra de idéer jag har och tar även på mig att ta fram strukturen för broschyren så att det blir ordentligt gjort."]],
        ["Vad passar bäst in på dig?",
         ["Livlig & uppmärksamhetskrävande", "Korrekt & eftertänksam", "Snabb & bossig",
          "Vänlig & försiktig"]],
        [
                "Du är på en stor invigningsfest för en ny ungdomsgård. Där är många du inte känner. Hur tänker och agerar du i början av festen?",
                [
                        "Jag gillar inte stora grupper så försöker hitta någon jag har gemensamma intressen med. Det kan bli lite jobbigt eftersom jag då måste småprata först och jag inte är superbra på det. Men hittar jag rätt personer kan det bli trevligt med en intressant diskussion i lugn och ro i ett hörn.",
                        "Superkul! Jag minglar runt och snackar med alla. Tar kvällen som den kommer, skämtar, skrattar och har inget emot att stå i centrum om det skulle råka bli så.",
                        "Jag småpratar med andra om trevliga grejer, kollar om de som fixat festen behöver hjälp och går kanske fram till någon som verkar ensam så att hen inte känner sig utanför.",
                        "Jag gillar att prata med andra och berätta om något spännande eller kul jag sysslar med. Jag är inte heller rädd för att kasta mig in i hetsig diskussion som verkar intressant, även om de andra har en annan åsikt än vad jag har."]],
        ["Hur pluggar du helst inför stora prov?",
         [
                 "Tillsammans med en eller ett par kompisar så kan vi hjälpa varandra och ha det trevligt under tiden.",
                 "Det beror lite på ämnet, men jag brukar läsa effektivt på slutet och så mycket som krävs för det betyg jag vill ha. Jag brukar ha koll!",
                 "Det är lite olika hur jag känner mig inspirerad. Ibland pluggar jag själv, ibland med andra, det brukar lösa sig.",
                 "Jag pluggar bäst ostört och på egen hand. Är bra på att systematiskt plugga in saker, särskilt om ämnet intresserar mig."]],
        [
                "En kompis nya cykel har blivit stulen. Trots att den var fastlåst vid cykelställen bakom skolan verkar någon ha hunnit kapa låset utan att ha blivit upptäckt. Hur reagerar du?",
                [
                        "Jag blir upprörd och säger att jag tänker ta upp med elevrådet eller rektorn att cykelställen borde flyttas till en plats med bättre uppsikt så att inte fler drabbas. ",
                        "Jag berättar att jag alltid bruka använda två lås så att risken för denna typ av händelser minimeras.",
                        "Jag kommer på att vi kan anordna en fest och ta inträde för att samla in pengar till en ny cykel till vår kompis. Jag sprider infon via mitt kontaktnät på sociala medier. Varför inte vända detta till något kul?",
                        "Jag kramar om min kompis och tröstar hen, frågar hur det känns osv."]],
        ["Vad är viktigast av följande i ett jobb/grupparbete?",
         ["Att jag får hålla på med intressanta uppgifter och fördjupa mig i dem",
          "Att jag får ha idéer och skoja till det",
          "Att jag är tillsammans med trevliga personer och får visa att jag är en bra kompis",
          "Att jag får göra utvecklande uppgifter och visa vad jag kan"]],
        ["På vilket sätt vill du helst arbeta med människor",
         ["Jag gillar när folk gör som jag föreslår",
          "Jag gillar när alla har koll på saker och inte fattar förhastade beslut",
          "Jag gillar när alla är överens",
          "Jag gillar när jag har kul och det händer nya saker under tiden"]],
        [
                "Du och några klasskompisar ska lösa en uppgift tillsammans. Hur ska det vara för att du ska trivas bäst?",
                ["Jag gillar när folk gör som jag föreslår",
                 "Jag gillar när alla har koll på saker och inte fattar förhastade beslut",
                 "Jag gillar när alla är överens",
                 "Jag gillar när jag har kul och det händer nya saker under tiden"]],
        [
                "Om någon dissar din jättebra plan om hur något ska göras tycker du troligtvis att de är…",
                ["…för kritiska", "…korkade", "…oseriösa", "…taskiga"]],
        ["Vilket av följande skulle du helst göra i ett jobb?",
         ["Se till att andra mår bra och får bra service",
          "Bestämma vad vi ska göra för att uppnå resultat",
          "Ta fram fakta, analysera vad som är fel och sedan lösa det",
          "Hjälpa andra att bli motiverade"]],
        ["Vem i Bamse identifierar du dig mest med?",
         ["Spralliga Mini Hopp", "Modiga Nalle-Maja", "Finurliga Skalman", "Hjälpsamma Bamse"]],
        ["Vilken Astrid Lindgren-karaktär identifierar du dig mest med?",
         ["Orubbliga rövarhövdingen Mattis från Ronja", "Visa Skalle-Per från Ronja Rövardotter",
          "Fridsamma drängen Alfred från Emil i Lönneberga", "Impulsiva Emil i Lönneberga"]],
        ["Vilken Mumin-karaktär identifierar du dig mest med?",
         ["Filosofiska Snusmumriken", "Omtänksamma Muminmamman", "Nyfikna Mumintrollet",
          "Viljestarka Lilla My"]],
        ["Vilken av dessa animerade karaktärer identifierar du dig mest med?",
         ["Partyglada Poppy i Trolls, som tar livet med en klackspark",
          "Drivna Vaiana, som går sin egen väg", "Skärpta Liza Simpson, som har ordning på allt",
          "Uthålliga Askungen, som aldrig blir arg på någon"]],
]

answers = [
        ['s', 'd', 'c', 'i'],
        ['d', 's', 'i', 'c'],
        ['d', 's', 'i', 'c'],
        ['c', 'd', 's', 'i'],
        ['d', 'i', 'c', 's'],
        ['s', 'd', 'c', 'i'],
        ['i', 'c', 's', 'd'],
        ['i', 'c', 'd', 's'],
        ['c', 'i', 's', 'd'],
        ['s', 'd', 'i', 'c'],
        ['d', 'c', 'i', 's'],
        ['c', 'i', 's', 'd'],
        ['s', 'd', 'c', 'i'],
        ['d', 'c', 's', 'i'],
        ['i', 'd', 'c', 's'],
        ['s', 'd', 'c', 'i'],
        ['i', 'd', 'c', 's'],
        ['d', 'c', 's', 'i'],
        ['c', 's', 'i', 'd'],
        ['i', 'd', 'c', 's'],
]